[profile.default]
src = '.'
out = 'out'
libs = ['lib']
solc = '0.8.17'
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[etherscan]
# Add your Etherscan API key for contract verification
base-sepolia = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
base-sepolia = "${BASE_SEPOLIA_RPC_URL}"
